### PR TITLE
Clarify readme

### PR DESCRIPTION
**Pull request by sdellis**

### CODE REVIEW

**Comment by kevinreiss** [comment]
@sdellis can you rebase this to one commit?

**Comment by sdellis** [comment]
Does that do the trick, @kevinreiss ?

**Comment by kevinreiss** [comment]
It still looks there are four commits here. It would be good to get that down to one. I usually use the interactive rebase approach described here: https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history. I usually rebase against the master branch. If you do that make sure you have the most recent copy of that branch in your local git repo. The"f" - fixup command is what I use to squash commits without leaving their original commit message. After a successful rebase you will need to do a force push on your working branch to update the PR.

**Comment by sdellis** [comment]
Hm... that is what I used too.  Sorry, I watched Jon do this with PULFA, but haven't done this on my own yet.  So, can I rebase against the master branch before the commits are in there?

**Comment by sdellis** [comment]
Abandoning this PR.

**Pull request closed without merging**
